name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
        cache: maven

    - name: Build project with Maven
      run: |
        mvn -B compile jib:build \
          -Djib.to.image=docker.io/mbocek/evidence-computer:latest \
          -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }} \
          --file pom.xml
